spring:
  application:
    name: smart-messaging-system
  
  # 기본 프로필을 local로 지정 (로컬 개발용)
  profiles:
    active: local

  # 공통 Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # 정적 리소스 캐시 버스팅(Cache Busting) 설정: CSS/JS 수정 시 브라우저 캐시 자동 갱신
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

# MyBatis 공통 설정
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.example.smartmessaging.dto   # dto 하위의 모든 패키지(vo, response, request) 자동 별칭 등록
  configuration:
    map-underscore-to-camel-case: true

# 콘솔 로그 설정
logging:
  level:
    root: info
    com.example.smartmessaging.mapper: debug

server:
  port: 8080

openai:
  moderation:
    base-url: https://api.openai.com
    api-key:
    model: omni-moderation-latest
    enabled: true