-- 실제 발송 허용 고객/채널 화이트리스트 테이블
--
-- 목적
--   대량 캠페인 발송은 기본적으로 Mock 발송으로 처리한다.
--   이 테이블에 등록된 고객(customer) + 채널(channel) 조합만 Solapi, Email, Kakao 같은 외부 발송 API를 실제 호출할 수 있다.
--
-- 설계 기준
--   - 수신자 정보는 customer 테이블을 기준으로 관리한다.
--   - 발송 채널은 channel 테이블을 기준으로 관리한다.
--   - 이 테이블은 customer와 channel 사이에서 실제 발송 허용 여부만 관리하는 관계 테이블이다.
--   - 전화번호/이메일 같은 실제 수신값은 중복 저장하지 않고 customer 테이블의 최신 값을 사용한다.
--
-- 사용 방법
--   1. 이 DDL을 Oracle DB 스키마에 수동으로 실행한다.
--   2. 실제 메시지를 받아도 되는 팀원/테스트 고객을 customer 테이블에 등록한다.
--   3. 해당 고객이 실제 수신해도 되는 채널만 channel_id와 함께 등록한다.
--   4. 잠시 막아야 하는 경우 삭제하지 말고 is_active = 0 으로 비활성화한다.
--
-- 예시
--   customer_id = 10, channel_id = SMS 채널 ID   -> 해당 고객에게 SMS 실제 발송 허용
--   customer_id = 10, channel_id = EMAIL 채널 ID -> 해당 고객에게 EMAIL 실제 발송 허용
--
-- 현재 프로젝트는 Flyway/Liquibase를 사용하지 않으므로 이 파일은 문서 겸 수동 실행용 DDL이다.

CREATE TABLE send_real_recipient_whitelist (
    -- 내부 식별용 기본키
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 실제 발송을 허용할 고객 ID
    -- customer.id를 참조한다.
    customer_id NUMBER NOT NULL,

    -- 실제 발송을 허용할 채널 ID
    -- channel.id를 참조한다.
    channel_id  NUMBER NOT NULL,

    -- 등록 사유나 담당자 확인용 메모
    -- 예: 'QA 팀 휴대폰 - 홍길동'
    description VARCHAR2(500),

    -- 1이면 실제 발송 허용, 0이면 행은 유지하지만 실제 발송 차단
    is_active   NUMBER(1) DEFAULT 1 NOT NULL,

    -- 프로젝트 공통 감사 컬럼
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  NUMBER,
    updated_by  NUMBER,
    is_deleted  NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_send_real_whitelist_active CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_send_real_whitelist_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_send_real_whitelist_customer FOREIGN KEY (customer_id) REFERENCES customer(id),
    CONSTRAINT fk_send_real_whitelist_channel FOREIGN KEY (channel_id) REFERENCES channel(id),

    -- 같은 고객/채널 조합이 동일한 삭제 상태로 중복 등록되는 것을 방지한다.
    CONSTRAINT uk_send_real_whitelist_customer_channel UNIQUE (customer_id, channel_id, is_deleted)
);

-- MessageSender가 실제 발송 여부를 빠르게 조회하기 위한 인덱스
CREATE INDEX idx_send_real_whitelist_lookup
    ON send_real_recipient_whitelist (customer_id, channel_id, is_active, is_deleted);

COMMENT ON TABLE send_real_recipient_whitelist IS '외부 발송 API 실제 호출을 허용할 고객/채널 화이트리스트';
COMMENT ON COLUMN send_real_recipient_whitelist.id IS '기본키';
COMMENT ON COLUMN send_real_recipient_whitelist.customer_id IS '실제 발송을 허용할 고객 ID. customer.id 참조';
COMMENT ON COLUMN send_real_recipient_whitelist.channel_id IS '실제 발송을 허용할 채널 ID. channel.id 참조';
COMMENT ON COLUMN send_real_recipient_whitelist.description IS '화이트리스트 등록 사유 또는 운영 메모';
COMMENT ON COLUMN send_real_recipient_whitelist.is_active IS '활성 여부. 1: 실제 발송 허용, 0: 실제 발송 차단';
COMMENT ON COLUMN send_real_recipient_whitelist.created_at IS '생성 일시';
COMMENT ON COLUMN send_real_recipient_whitelist.updated_at IS '수정 일시';
COMMENT ON COLUMN send_real_recipient_whitelist.created_by IS '생성자 사용자 ID';
COMMENT ON COLUMN send_real_recipient_whitelist.updated_by IS '수정자 사용자 ID';
COMMENT ON COLUMN send_real_recipient_whitelist.is_deleted IS '소프트 삭제 여부. 0: 정상, 1: 삭제';
