-- 실제 발송 허용 고객 화이트리스트 테이블
--
-- 목적
--   대량 캠페인 발송은 기본적으로 Mock 발송으로 처리한다.
--   이 테이블에 등록된 수신번호/이메일 정보 및 수신 채널 동의 조합만 
--   Solapi, Email, Kakao 같은 외부 발송 API를 실제 호출할 수 있다.
--
-- 설계 기준
--   - 이 테이블은 customer 테이블의 구조(형태)와 동일하게 분리된 독립 테이블이다.
--   - 수신자 정보(이름, 번호, 이메일 등)를 독자적으로 저장하며, is_active가 1인 경우만 실발송 대상으로 인정한다.
--   - 고객-채널 수신동의 연관 관계 역시 별도의 매핑 테이블(send_real_whitelist_consent)을 통해 분리 관리한다.
--
-- 사용 방법
--   1. 이 DDL을 Oracle DB 스키마에 수동으로 실행한다.
--   2. 실제 메시지를 수신할 테스트 대상자를 이 테이블(send_real_recipient_whitelist)에 등록한다.
--   3. 해당 대상자가 수신해도 되는 채널에 대한 동의 이력을 send_real_whitelist_consent 테이블에 채널 ID와 함께 등록한다.
--   4. 잠시 막아야 하는 경우 is_active = 0 으로 비활성화하거나, consent의 is_consented = 0 으로 조율한다.

CREATE TABLE send_real_recipient_whitelist (
    -- 내부 식별용 기본키
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 수신 대상자 정보 (고객 테이블과 동일)
    phone          VARCHAR2(20) NOT NULL,
    name           VARCHAR2(100),
    email          VARCHAR2(100),
    customer_type  VARCHAR2(50) DEFAULT 'NORMAL',
    is_ad_blocked  NUMBER(1) DEFAULT 0 NOT NULL,
    birth_date     DATE,
    gender         VARCHAR2(10),
    last_active_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    joined_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    -- 화이트리스트 메모
    description    VARCHAR2(500),

    -- 1이면 실제 발송 허용, 0이면 전체 차단
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,

    -- 프로젝트 공통 감사 컬럼
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by     NUMBER,
    updated_by     NUMBER,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_send_real_whitelist_active CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_send_real_whitelist_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT chk_send_real_whitelist_ad CHECK (is_ad_blocked IN (0, 1)),
    
    -- 동일한 수신 번호가 정상 상태에서 중복 등록되는 것을 방지
    CONSTRAINT uk_send_real_whitelist_phone UNIQUE (phone, is_deleted)
);

-- 화이트리스트 조회 성능 향상을 위한 인덱스
CREATE INDEX idx_send_real_whitelist_lookup
    ON send_real_recipient_whitelist (phone, email, is_active, is_deleted);


-- 실제 발송 허용 고객의 채널별 수신 동의 테이블 (customer_channel_consent 구조 모방)
CREATE TABLE send_real_whitelist_consent (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 화이트리스트 고객 ID 참조
    whitelist_id  NUMBER NOT NULL,
    
    -- 동의할 채널 ID (channel.id 참조)
    channel_id    NUMBER NOT NULL,
    
    -- 동의 여부 (1: 동의, 0: 거부)
    is_consented  NUMBER(1) DEFAULT 1 NOT NULL,
    
    -- 프로젝트 공통 감사 컬럼
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_by     NUMBER,
    updated_by     NUMBER,
    is_deleted     NUMBER(1) DEFAULT 0 NOT NULL,
    
    CONSTRAINT chk_send_real_consent_val CHECK (is_consented IN (0, 1)),
    CONSTRAINT chk_send_real_consent_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_send_real_consent_whitelist FOREIGN KEY (whitelist_id) REFERENCES send_real_recipient_whitelist(id) ON DELETE CASCADE,
    CONSTRAINT fk_send_real_consent_channel FOREIGN KEY (channel_id) REFERENCES channel(id),
    
    -- 한 고객에 대해 한 채널당 하나의 동의 상태만 유지
    CONSTRAINT uk_send_real_consent_mapping UNIQUE (whitelist_id, channel_id, is_deleted)
);

CREATE INDEX idx_send_real_consent_lookup
    ON send_real_whitelist_consent (whitelist_id, channel_id, is_consented, is_deleted);


COMMENT ON TABLE send_real_recipient_whitelist IS '실제 발송 허용 수신자(고객 형태 복제)';
COMMENT ON COLUMN send_real_recipient_whitelist.id IS '기본키';
COMMENT ON COLUMN send_real_recipient_whitelist.phone IS '수신 전화번호';
COMMENT ON COLUMN send_real_recipient_whitelist.name IS '수신자 이름';
COMMENT ON COLUMN send_real_recipient_whitelist.email IS '수신 이메일';
COMMENT ON COLUMN send_real_recipient_whitelist.customer_type IS '고객 유형';
COMMENT ON COLUMN send_real_recipient_whitelist.is_ad_blocked IS '광고 거부 여부';
COMMENT ON COLUMN send_real_recipient_whitelist.birth_date IS '생년월일';
COMMENT ON COLUMN send_real_recipient_whitelist.gender IS '성별';
COMMENT ON COLUMN send_real_recipient_whitelist.description IS '메모';
COMMENT ON COLUMN send_real_recipient_whitelist.is_active IS '활성화 여부(1: 허용, 0: 일시 차단)';

COMMENT ON TABLE send_real_whitelist_consent IS '실제 발송 허용 수신자의 채널 수신 동의 상태';
COMMENT ON COLUMN send_real_whitelist_consent.id IS '기본키';
COMMENT ON COLUMN send_real_whitelist_consent.whitelist_id IS '화이트리스트 고객 ID 참조';
COMMENT ON COLUMN send_real_whitelist_consent.channel_id IS '채널 ID 참조';
COMMENT ON COLUMN send_real_whitelist_consent.is_consented IS '수신 동의 여부(1: 동의, 0: 거부)';

commit;
